tasks::qp::Equality Class Reference
tasks::qp::Equality Class Reference abstract
#include <QPSolver.h>
Public Member Functions
virtual ~Equality ()
virtual int maxEq () const =0
virtual int nrEq () const
virtual const Eigen::MatrixXd & AEq () const =0
virtual const Eigen::VectorXd & bEq () const =0
virtual std::string nameEq () const =0
virtual std::string descEq (const std::vector< rbd::MultiBody > &mbs, int i)=0
void addToSolver (QPSolver &sol)
void removeFromSolver (QPSolver &sol)
Constructor & Destructor Documentation
virtual tasks::qp::Equality::~Equality () inline virtual
Member Function Documentation
void tasks::qp::Equality::addToSolver (QPSolver & sol) inline
References tasks::qp::QPSolver::addEqualityConstraint().
virtual const Eigen::MatrixXd& tasks::qp::Equality::AEq () const pure virtual
Referenced by tasks::qp::printConstr().
virtual const Eigen::VectorXd& tasks::qp::Equality::bEq () const pure virtual
Referenced by tasks::qp::printConstr().
virtual std::string tasks::qp::Equality::descEq (const std::vector< rbd::MultiBody > & mbs, int i) pure virtual
Referenced by tasks::qp::constr_traits< Equality >::desc().
virtual int tasks::qp::Equality::maxEq () const pure virtual
Referenced by tasks::qp::constr_traits< Equality >::maxLines().
virtual std::string tasks::qp::Equality::nameEq () const pure virtual
Referenced by tasks::qp::constr_traits< Equality >::name().
virtual int tasks::qp::Equality::nrEq () const inline virtual
Referenced by tasks::qp::constr_traits< Equality >::nrLines().
void tasks::qp::Equality::removeFromSolver (QPSolver & sol) inline
References tasks::qp::QPSolver::removeEqualityConstraint().