tasks::qp::Inequality Class Reference
tasks::qp::Inequality Class Reference abstract
#include <QPSolver.h>
Public Member Functions
virtual ~Inequality ()
virtual int maxInEq () const =0
virtual int nrInEq () const
virtual const Eigen::MatrixXd & AInEq () const =0
virtual const Eigen::VectorXd & bInEq () const =0
virtual std::string nameInEq () const =0
virtual std::string descInEq (const std::vector< rbd::MultiBody > &mbs, int i)=0
void addToSolver (QPSolver &sol)
void removeFromSolver (QPSolver &sol)
Constructor & Destructor Documentation
virtual tasks::qp::Inequality::~Inequality () inline virtual
Member Function Documentation
void tasks::qp::Inequality::addToSolver (QPSolver & sol) inline
References tasks::qp::QPSolver::addInequalityConstraint().
virtual const Eigen::MatrixXd& tasks::qp::Inequality::AInEq () const pure virtual
Referenced by tasks::qp::printConstr().
virtual const Eigen::VectorXd& tasks::qp::Inequality::bInEq () const pure virtual
Referenced by tasks::qp::printConstr().
virtual std::string tasks::qp::Inequality::descInEq (const std::vector< rbd::MultiBody > & mbs, int i) pure virtual
Referenced by tasks::qp::constr_traits< Inequality >::desc().
virtual int tasks::qp::Inequality::maxInEq () const pure virtual
Referenced by tasks::qp::constr_traits< Inequality >::maxLines().
virtual std::string tasks::qp::Inequality::nameInEq () const pure virtual
Referenced by tasks::qp::constr_traits< Inequality >::name().
virtual int tasks::qp::Inequality::nrInEq () const inline virtual
Referenced by tasks::qp::constr_traits< Inequality >::nrLines().
void tasks::qp::Inequality::removeFromSolver (QPSolver & sol) inline
References tasks::qp::QPSolver::removeInequalityConstraint().