tasks::qp::GenInequality Class Reference
tasks::qp::GenInequality Class Reference abstract
#include <Tasks/QPSolver.h>
Public Member Functions
virtual ~GenInequality ()
virtual int maxGenInEq () const =0
virtual int nrGenInEq () const
virtual const Eigen::MatrixXd & AGenInEq () const =0
virtual const Eigen::VectorXd & LowerGenInEq () const =0
virtual const Eigen::VectorXd & UpperGenInEq () const =0
virtual std::string nameGenInEq () const =0
virtual std::string descGenInEq (const std::vector< rbd::MultiBody > &mbs, int i)=0
void addToSolver (QPSolver &sol)
void removeFromSolver (QPSolver &sol)
Constructor & Destructor Documentation
virtual tasks::qp::GenInequality::~GenInequality () inline virtual
Member Function Documentation
void tasks::qp::GenInequality::addToSolver (QPSolver & sol) inline
References tasks::qp::QPSolver::addGenInequalityConstraint().
virtual const Eigen::MatrixXd& tasks::qp::GenInequality::AGenInEq () const pure virtual
Referenced by tasks::qp::printConstr().
virtual std::string tasks::qp::GenInequality::descGenInEq (const std::vector< rbd::MultiBody > & mbs, int i) pure virtual
Referenced by tasks::qp::constr_traits< GenInequality >::desc().
virtual const Eigen::VectorXd& tasks::qp::GenInequality::LowerGenInEq () const pure virtual
Referenced by tasks::qp::printConstr().
virtual int tasks::qp::GenInequality::maxGenInEq () const pure virtual
Referenced by tasks::qp::constr_traits< GenInequality >::maxLines().
virtual std::string tasks::qp::GenInequality::nameGenInEq () const pure virtual
Referenced by tasks::qp::constr_traits< GenInequality >::name().
virtual int tasks::qp::GenInequality::nrGenInEq () const inline virtual
Referenced by tasks::qp::constr_traits< GenInequality >::nrLines().
void tasks::qp::GenInequality::removeFromSolver (QPSolver & sol) inline
References tasks::qp::QPSolver::removeGenInequalityConstraint().
virtual const Eigen::VectorXd& tasks::qp::GenInequality::UpperGenInEq () const pure virtual
Referenced by tasks::qp::printConstr().