tasks::qp Namespace Reference
tasks::qp Namespace Reference
Classes
struct BilateralContact
Model of a generic contacts.
class Bound
class BoundedSpeedConstr
Constraint some link velocity in link frame by direct integration.
class CollisionConstr
Avoid that too robot links enter into collision based on a velocity damper.
class CoMIncPlaneConstr
Prevent robot CoM to go out of a convex hull.
class CoMTask
struct constr_traits
struct constr_traits< Equality >
struct constr_traits< GenInequality >
struct constr_traits< Inequality >
class Constraint
class ConstraintFunction
class ContactAccConstr
Contact constraint by targeting a null acceleration.
class ContactConstr
Common contact constraint computation.
class ContactConstrCommon
Manage modifier on contact constraint.
struct ContactId
Unique identifier for a contact.
class ContactPosConstr
Contact constraint by targeting a constant frame.
class ContactSpeedConstr
Contact constraint by targeting a null velocity.
class ContactTask
class DamperJointLimitsConstr
Avoid to reach articular position and velocity limits based on a velocity damper.
class Equality
struct FrictionCone
Linearized friction cone generator.
class GazeTask
class GenInequality
class GenQPSolver
Generic QP solver abstract interface.
class GripperTorqueConstr
class GripperTorqueTask
class HighLevelTask
class ImageConstr
Generalized Image Point Constraint This can be used as either a Field of View constraint or an Occlusion avoidance constraint.
class Inequality
struct JointGains
class JointLimitsConstr
Avoid to reach articular position limits based on direct integration.
class JointsSelector
struct JointStiffness
class LinVelocityTask
class LSSOLQPSolver
GenQPSolver interface implementation with the LSSOL QP solver.
class MomentumTask
class MotionConstr
class MotionConstrCommon
class MotionPolyConstr
Use polynome in function of q to compute torque limits.
class MotionSpringConstr
class MultiCoMTask
class MultiRobotTransformTask
class OrientationTask
class OrientationTrackingTask
class PIDTask
class PositionBasedVisServoTask
class PositionTask
class PositiveLambda
class PostureTask
class QLDQPSolver
GenQPSolver interface implementation with the QLD QP solver.
class QPSolver
class RelativeDistTask
class SetPointTask
class SetPointTaskCommon
class SolverData
struct SpringJoint
class SurfaceOrientationTask
class SurfaceTransformTask
TransformTask in surface frame.
class TargetObjectiveTask
class Task
class TorqueTask
class TrackingTask
class TrajectoryTask
class TransformTask
TransformTask in world or user frame.
class TransformTaskCommon
struct UnilateralContact
Model of a planar contacts.
class VectorOrientationTask
Functions
void fillQC (const std::vector< Task *> &tasks, int nrVars, Eigen::MatrixXd &Q, Eigen::VectorXd &C)
Fill the \(Q \) matrix and the \(c \) vector based on the task list.
void reduceQC (const Eigen::MatrixXd &QFull, const Eigen::VectorXd &CFull, Eigen::MatrixXd &Q, Eigen::VectorXd &C, const std::vector< int > &fullToReduced, const std::vector< int > &reducedToFull, const std::vector< std::tuple< int, int, double >> &dependencies)
Reduce \(Q \) matrix and the \(c \) vector based on the dependencies list.
int fillEq (const std::vector< Equality *> &eq, int nrVars, int nrALines, Eigen::MatrixXd &A, Eigen::VectorXd &AL, Eigen::VectorXd &AU)
Fill the \(A \) matrix and the \(L \) and \(U \) bounds vectors based on the equality constaint list.
int fillInEq (const std::vector< Inequality *> &inEq, int nrVars, int nrALines, Eigen::MatrixXd &A, Eigen::VectorXd &AL, Eigen::VectorXd &AU)
Fill the \(A \) matrix and the \(L \) and \(U \) bounds vectors based on the inequality constaint list.
int fillGenInEq (const std::vector< GenInequality *> &genInEq, int nrVars, int nrALines, Eigen::MatrixXd &A, Eigen::VectorXd &AL, Eigen::VectorXd &AU)
Fill the \(A \) matrix and the \(L \) and \(U \) bounds vectors based on the general inequality constaint list.
int fillEq (const std::vector< Equality *> &eq, int nrVars, int nrALines, Eigen::MatrixXd &A, Eigen::VectorXd &b)
Fill the \(A \) matrix and the \(b \) vectors based on the equality constaint list.
int fillInEq (const std::vector< Inequality *> &inEq, int nrVars, int nrALines, Eigen::MatrixXd &A, Eigen::VectorXd &b)
Fill the \(A \) matrix and the \(b \) vectors based on the inequality constaint list.
int fillGenInEq (const std::vector< GenInequality *> &genInEq, int nrVars, int nrALines, Eigen::MatrixXd &A, Eigen::VectorXd &b)
Fill the \(A \) matrix and the \(b \) vectors based on the general inequality constaint list.
void fillBound (const std::vector< Bound *> &bounds, Eigen::VectorXd &XL, Eigen::VectorXd &XU)
Fill the \(L \) and \(U \) bounds vectors based on the bound constaint list.
void reduceA (const Eigen::MatrixXd &AFull, Eigen::MatrixXd &A, const std::vector< int > &fullToReduced, const std::vector< int > &reducedToFull, const std::vector< std::tuple< int, int, double >> &dependencies)
Reduce \(A \) matrix based on the dependencies list.
void reduceBound (const Eigen::VectorXd &XLFull, Eigen::VectorXd &XL, const Eigen::VectorXd &XUFull, Eigen::VectorXd &XU, const std::vector< int > &fullToReduced, const std::vector< int > &reducedToFull, const std::vector< std::tuple< int, int, double >> &dependencies)
Reduce bounds vector based on the dependencies list.
void expandResult (const Eigen::VectorXd &result, Eigen::VectorXd &resultFull, const std::vector< int > &reducedToFull, const std::vector< std::tuple< int, int, double >> &dependencies)
Return the full variable from the reduced variable.
template<typename T >
std::ostream & printConstr (const Eigen::VectorXd &result, T *constr, int line, std::ostream &out)
template<>
std::ostream & printConstr (const Eigen::VectorXd &result, Equality *constr, int line, std::ostream &out)
template<>
std::ostream & printConstr (const Eigen::VectorXd &result, Inequality *constr, int line, std::ostream &out)
template<>
std::ostream & printConstr (const Eigen::VectorXd &result, GenInequality *constr, int line, std::ostream &out)
template<typename T >
std::ostream & constrErrorMsg (const std::vector< rbd::MultiBody > &mbs, const Eigen::VectorXd &result, int ALine, const std::vector< T *> &constr, int &start, int &end, std::ostream &out)
TASKS_DLLAPI GenQPSolver * createQPSolver (const std::string &name)
Factory to create GenQPSolver implementation.
TASKS_DLLAPI sch::Matrix4x4 tosch (const sva::PTransformd &t)
Convert a sch-core transformation matrix to a sva::PTransformd matrix.
int findJointFromVector (const rbd::MultiBody &mb, int line, bool withBase)
bool compareDof (const rbd::MultiBody &mb1, const rbd::MultiBody &mb2)
Variables
static const double DIAG_CONSTANT = 1e-4
Function Documentation
compareDof()
bool tasks::qp::compareDof (const rbd::MultiBody & mb1, const rbd::MultiBody & mb2) inline
References rbd::MultiBody::nrDof().
constrErrorMsg()
template<typename T > std::ostream& tasks::qp::constrErrorMsg (const std::vector< rbd::MultiBody > & mbs, const Eigen::VectorXd & result, int ALine, const std::vector< T *> & constr, int & start, int & end, std::ostream & out) inline
References printConstr().
createQPSolver()
TASKS_DLLAPI GenQPSolver* tasks::qp::createQPSolver (const std::string & name)
Factory to create GenQPSolver implementation.
Two argument are supported QLD and LSSOL.
expandResult()
void tasks::qp::expandResult (const Eigen::VectorXd & result, Eigen::VectorXd & resultFull, const std::vector< int > & reducedToFull, const std::vector< std::tuple< int, int, double >> & dependencies) inline
Return the full variable from the reduced variable.
References printConstr().
fillBound()
void tasks::qp::fillBound (const std::vector< Bound *> & bounds, Eigen::VectorXd & XL, Eigen::VectorXd & XU) inline
Fill the \(L \) and \(U \) bounds vectors based on the bound constaint list.
fillEq() [1/2]
int tasks::qp::fillEq (const std::vector< Equality *> & eq, int nrVars, int nrALines, Eigen::MatrixXd & A, Eigen::VectorXd & AL, Eigen::VectorXd & AU) inline
Fill the \(A \) matrix and the \(L \) and \(U \) bounds vectors based on the equality constaint list.
fillEq() [2/2]
int tasks::qp::fillEq (const std::vector< Equality *> & eq, int nrVars, int nrALines, Eigen::MatrixXd & A, Eigen::VectorXd & b) inline
Fill the \(A \) matrix and the \(b \) vectors based on the equality constaint list.
fillGenInEq() [1/2]
int tasks::qp::fillGenInEq (const std::vector< GenInequality *> & genInEq, int nrVars, int nrALines, Eigen::MatrixXd & A, Eigen::VectorXd & AL, Eigen::VectorXd & AU) inline
Fill the \(A \) matrix and the \(L \) and \(U \) bounds vectors based on the general inequality constaint list.
fillGenInEq() [2/2]
int tasks::qp::fillGenInEq (const std::vector< GenInequality *> & genInEq, int nrVars, int nrALines, Eigen::MatrixXd & A, Eigen::VectorXd & b) inline
Fill the \(A \) matrix and the \(b \) vectors based on the general inequality constaint list.
fillInEq() [1/2]
int tasks::qp::fillInEq (const std::vector< Inequality *> & inEq, int nrVars, int nrALines, Eigen::MatrixXd & A, Eigen::VectorXd & AL, Eigen::VectorXd & AU) inline
Fill the \(A \) matrix and the \(L \) and \(U \) bounds vectors based on the inequality constaint list.
fillInEq() [2/2]
int tasks::qp::fillInEq (const std::vector< Inequality *> & inEq, int nrVars, int nrALines, Eigen::MatrixXd & A, Eigen::VectorXd & b) inline
Fill the \(A \) matrix and the \(b \) vectors based on the inequality constaint list.
fillQC()
void tasks::qp::fillQC (const std::vector< Task *> & tasks, int nrVars, Eigen::MatrixXd & Q, Eigen::VectorXd & C) inline
Fill the \(Q \) matrix and the \(c \) vector based on the task list.
References DIAG_CONSTANT.
findJointFromVector()
int tasks::qp::findJointFromVector (const rbd::MultiBody & mb, int line, bool withBase) inline
References rbd::Joint::dof(), rbd::MultiBody::joint(), and rbd::MultiBody::nrJoints().
printConstr() [1/4]
template<typename T > std::ostream& tasks::qp::printConstr (const Eigen::VectorXd & result, T * constr, int line, std::ostream & out)
Referenced by constrErrorMsg(), and expandResult().
printConstr() [2/4]
template<> std::ostream& tasks::qp::printConstr (const Eigen::VectorXd & result, Equality * constr, int line, std::ostream & out) inline
References tasks::qp::Equality::AEq(), and tasks::qp::Equality::bEq().
printConstr() [3/4]
template<> std::ostream& tasks::qp::printConstr (const Eigen::VectorXd & result, Inequality * constr, int line, std::ostream & out) inline
References tasks::qp::Inequality::AInEq(), and tasks::qp::Inequality::bInEq().
printConstr() [4/4]
template<> std::ostream& tasks::qp::printConstr (const Eigen::VectorXd & result, GenInequality * constr, int line, std::ostream & out) inline
References tasks::qp::GenInequality::AGenInEq(), tasks::qp::GenInequality::LowerGenInEq(), and tasks::qp::GenInequality::UpperGenInEq().
reduceA()
void tasks::qp::reduceA (const Eigen::MatrixXd & AFull, Eigen::MatrixXd & A, const std::vector< int > & fullToReduced, const std::vector< int > & reducedToFull, const std::vector< std::tuple< int, int, double >> & dependencies) inline
Reduce \(A \) matrix based on the dependencies list.
reduceBound()
void tasks::qp::reduceBound (const Eigen::VectorXd & XLFull, Eigen::VectorXd & XL, const Eigen::VectorXd & XUFull, Eigen::VectorXd & XU, const std::vector< int > & fullToReduced, const std::vector< int > & reducedToFull, const std::vector< std::tuple< int, int, double >> & dependencies) inline
Reduce bounds vector based on the dependencies list.
If alpha is negative, the upper/lower bounds should be inverted
reduceQC()
void tasks::qp::reduceQC (const Eigen::MatrixXd & QFull, const Eigen::VectorXd & CFull, Eigen::MatrixXd & Q, Eigen::VectorXd & C, const std::vector< int > & fullToReduced, const std::vector< int > & reducedToFull, const std::vector< std::tuple< int, int, double >> & dependencies) inline
Reduce \(Q \) matrix and the \(c \) vector based on the dependencies list.
tosch()
TASKS_DLLAPI sch::Matrix4x4 tasks::qp::tosch (const sva::PTransformd & t)
Convert a sch-core transformation matrix to a sva::PTransformd matrix.
Variable Documentation
DIAG_CONSTANT
const double tasks::qp::DIAG_CONSTANT = 1e-4 static
Referenced by fillQC().