tasks::qp Namespace Reference
tasks::qp Namespace Reference
Classes
class GenQPSolver
Generic QP solver abstract interface.
class LSSOLQPSolver
GenQPSolver interface implementation with the LSSOL QP solver.
class QLDQPSolver
GenQPSolver interface implementation with the QLD QP solver.
class JointLimitsConstr
Avoid to reach articular position limits based on direct integration.
class DamperJointLimitsConstr
Avoid to reach articular position and velocity limits based on a velocity damper.
class CollisionConstr
Avoid that too robot links enter into collision based on a velocity damper.
class CoMIncPlaneConstr
Prevent robot CoM to go out of a convex hull.
class GripperTorqueConstr
class BoundedSpeedConstr
Constraint some link velocity in link frame by direct integration.
class ImageConstr
Generalized Image Point Constraint This can be used as either a Field of View constraint or an Occlusion avoidance constraint.
class ContactConstrCommon
Manage modifier on contact constraint.
class ContactConstr
Common contact constraint computation.
class ContactAccConstr
Contact constraint by targeting a null acceleration.
class ContactSpeedConstr
Contact constraint by targeting a null velocity.
class ContactPosConstr
Contact constraint by targeting a constant frame.
struct FrictionCone
Linearized friction cone generator.
struct ContactId
Unique identifier for a contact.
struct UnilateralContact
Model of a planar contacts.
struct BilateralContact
Model of a generic contacts.
class PositiveLambda
class MotionConstrCommon
class MotionConstr
struct SpringJoint
class MotionSpringConstr
class MotionPolyConstr
Use polynome in function of q to compute torque limits.
class QPSolver
class Constraint
class ConstraintFunction
class Equality
class Inequality
class GenInequality
class Bound
class Task
class HighLevelTask
struct constr_traits
struct constr_traits< Equality >
struct constr_traits< Inequality >
struct constr_traits< GenInequality >
class SolverData
class SetPointTaskCommon
class SetPointTask
class TrackingTask
class TrajectoryTask
class PIDTask
class TargetObjectiveTask
class JointsSelector
struct JointStiffness
struct JointGains
class TorqueTask
class PostureTask
class PositionTask
class OrientationTask
class TransformTaskCommon
class SurfaceTransformTask
TransformTask in surface frame.
class TransformTask
TransformTask in world or user frame.
class SurfaceOrientationTask
class GazeTask
class PositionBasedVisServoTask
class CoMTask
class MultiCoMTask
class MultiRobotTransformTask
class MomentumTask
class ContactTask
class GripperTorqueTask
class LinVelocityTask
class OrientationTrackingTask
class RelativeDistTask
class VectorOrientationTask
Functions
TASKS_DLLAPI GenQPSolver * createQPSolver (const std::string &name)
Factory to create GenQPSolver implementation.
void fillQC (const std::vector< Task * > &tasks, int nrVars, Eigen::MatrixXd &Q, Eigen::VectorXd &C)
Fill the \(Q \) matrix and the \(c \) vector based on the task list.
void reduceQC (const Eigen::MatrixXd &QFull, const Eigen::VectorXd &CFull, Eigen::MatrixXd &Q, Eigen::VectorXd &C, const std::vector< int > &fullToReduced, const std::vector< int > &reducedToFull, const std::vector< std::tuple< int, int, double >> &dependencies)
Reduce \(Q \) matrix and the \(c \) vector based on the dependencies list.
int fillEq (const std::vector< Equality * > &eq, int nrVars, int nrALines, Eigen::MatrixXd &A, Eigen::VectorXd &AL, Eigen::VectorXd &AU)
Fill the \(A \) matrix and the \(L \) and \(U \) bounds vectors based on the equality constaint list.
int fillInEq (const std::vector< Inequality * > &inEq, int nrVars, int nrALines, Eigen::MatrixXd &A, Eigen::VectorXd &AL, Eigen::VectorXd &AU)
Fill the \(A \) matrix and the \(L \) and \(U \) bounds vectors based on the inequality constaint list.
int fillGenInEq (const std::vector< GenInequality * > &genInEq, int nrVars, int nrALines, Eigen::MatrixXd &A, Eigen::VectorXd &AL, Eigen::VectorXd &AU)
Fill the \(A \) matrix and the \(L \) and \(U \) bounds vectors based on the general inequality constaint list.
int fillEq (const std::vector< Equality * > &eq, int nrVars, int nrALines, Eigen::MatrixXd &A, Eigen::VectorXd &b)
Fill the \(A \) matrix and the \(b \) vectors based on the equality constaint list.
int fillInEq (const std::vector< Inequality * > &inEq, int nrVars, int nrALines, Eigen::MatrixXd &A, Eigen::VectorXd &b)
Fill the \(A \) matrix and the \(b \) vectors based on the inequality constaint list.
int fillGenInEq (const std::vector< GenInequality * > &genInEq, int nrVars, int nrALines, Eigen::MatrixXd &A, Eigen::VectorXd &b)
Fill the \(A \) matrix and the \(b \) vectors based on the general inequality constaint list.
void fillBound (const std::vector< Bound * > &bounds, Eigen::VectorXd &XL, Eigen::VectorXd &XU)
Fill the \(L \) and \(U \) bounds vectors based on the bound constaint list.
void reduceA (const Eigen::MatrixXd &AFull, Eigen::MatrixXd &A, const std::vector< int > &fullToReduced, const std::vector< int > &reducedToFull, const std::vector< std::tuple< int, int, double >> &dependencies)
Reduce \(A \) matrix based on the dependencies list.
void reduceBound (const Eigen::VectorXd &XLFull, Eigen::VectorXd &XL, const Eigen::VectorXd &XUFull, Eigen::VectorXd &XU, const std::vector< int > &fullToReduced, const std::vector< int > &reducedToFull, const std::vector< std::tuple< int, int, double >> &dependencies)
Reduce bounds vector based on the dependencies list.
void expandResult (const Eigen::VectorXd &result, Eigen::VectorXd &resultFull, const std::vector< int > &reducedToFull, const std::vector< std::tuple< int, int, double >> &dependencies)
Return the full variable from the reduced variable.
template<typename T >
std::ostream & printConstr (const Eigen::VectorXd &result, T *constr, int line, std::ostream &out)
template<>
std::ostream & printConstr (const Eigen::VectorXd &result, Equality *constr, int line, std::ostream &out)
template<>
std::ostream & printConstr (const Eigen::VectorXd &result, Inequality *constr, int line, std::ostream &out)
template<>
std::ostream & printConstr (const Eigen::VectorXd &result, GenInequality *constr, int line, std::ostream &out)
template<typename T >
std::ostream & constrErrorMsg (const std::vector< rbd::MultiBody > &mbs, const Eigen::VectorXd &result, int ALine, const std::vector< T * > &constr, int &start, int &end, std::ostream &out)
TASKS_DLLAPI sch::Matrix4x4 tosch (const sva::PTransformd &t)
Convert a sch-core transformation matrix to a sva::PTransformd matrix.
int findJointFromVector (const rbd::MultiBody &mb, int line, bool withBase)
bool compareDof (const rbd::MultiBody &mb1, const rbd::MultiBody &mb2)
Variables
static const double DIAG_CONSTANT = 1e-4
Function Documentation
bool tasks::qp::compareDof (const rbd::MultiBody & mb1, const rbd::MultiBody & mb2) inline
References rbd::MultiBody::nrDof().
template<typename T > std::ostream& tasks::qp::constrErrorMsg (const std::vector< rbd::MultiBody > & mbs, const Eigen::VectorXd & result, int ALine, const std::vector< T * > & constr, int & start, int & end, std::ostream & out) inline
References printConstr().
TASKS_DLLAPI GenQPSolver* tasks::qp::createQPSolver (const std::string & name)
Factory to create GenQPSolver implementation.
Two argument are supported QLD and LSSOL.
void tasks::qp::expandResult (const Eigen::VectorXd & result, Eigen::VectorXd & resultFull, const std::vector< int > & reducedToFull, const std::vector< std::tuple< int, int, double >> & dependencies) inline
Return the full variable from the reduced variable.
void tasks::qp::fillBound (const std::vector< Bound * > & bounds, Eigen::VectorXd & XL, Eigen::VectorXd & XU) inline
Fill the \(L \) and \(U \) bounds vectors based on the bound constaint list.
int tasks::qp::fillEq (const std::vector< Equality * > & eq, int nrVars, int nrALines, Eigen::MatrixXd & A, Eigen::VectorXd & AL, Eigen::VectorXd & AU) inline
Fill the \(A \) matrix and the \(L \) and \(U \) bounds vectors based on the equality constaint list.
int tasks::qp::fillEq (const std::vector< Equality * > & eq, int nrVars, int nrALines, Eigen::MatrixXd & A, Eigen::VectorXd & b) inline
Fill the \(A \) matrix and the \(b \) vectors based on the equality constaint list.
int tasks::qp::fillGenInEq (const std::vector< GenInequality * > & genInEq, int nrVars, int nrALines, Eigen::MatrixXd & A, Eigen::VectorXd & AL, Eigen::VectorXd & AU) inline
Fill the \(A \) matrix and the \(L \) and \(U \) bounds vectors based on the general inequality constaint list.
int tasks::qp::fillGenInEq (const std::vector< GenInequality * > & genInEq, int nrVars, int nrALines, Eigen::MatrixXd & A, Eigen::VectorXd & b) inline
Fill the \(A \) matrix and the \(b \) vectors based on the general inequality constaint list.
int tasks::qp::fillInEq (const std::vector< Inequality * > & inEq, int nrVars, int nrALines, Eigen::MatrixXd & A, Eigen::VectorXd & AL, Eigen::VectorXd & AU) inline
Fill the \(A \) matrix and the \(L \) and \(U \) bounds vectors based on the inequality constaint list.
int tasks::qp::fillInEq (const std::vector< Inequality * > & inEq, int nrVars, int nrALines, Eigen::MatrixXd & A, Eigen::VectorXd & b) inline
Fill the \(A \) matrix and the \(b \) vectors based on the inequality constaint list.
void tasks::qp::fillQC (const std::vector< Task * > & tasks, int nrVars, Eigen::MatrixXd & Q, Eigen::VectorXd & C) inline
Fill the \(Q \) matrix and the \(c \) vector based on the task list.
References DIAG_CONSTANT.
int tasks::qp::findJointFromVector (const rbd::MultiBody & mb, int line, bool withBase) inline
References rbd::Joint::dof(), rbd::MultiBody::joint(), and rbd::MultiBody::nrJoints().
template<typename T > std::ostream& tasks::qp::printConstr (const Eigen::VectorXd & result, T * constr, int line, std::ostream & out)
Referenced by constrErrorMsg().
template<> std::ostream& tasks::qp::printConstr (const Eigen::VectorXd & result, Equality * constr, int line, std::ostream & out) inline
References tasks::qp::Equality::AEq(), and tasks::qp::Equality::bEq().
template<> std::ostream& tasks::qp::printConstr (const Eigen::VectorXd & result, Inequality * constr, int line, std::ostream & out) inline
References tasks::qp::Inequality::AInEq(), and tasks::qp::Inequality::bInEq().
template<> std::ostream& tasks::qp::printConstr (const Eigen::VectorXd & result, GenInequality * constr, int line, std::ostream & out) inline
References tasks::qp::GenInequality::AGenInEq(), tasks::qp::GenInequality::LowerGenInEq(), and tasks::qp::GenInequality::UpperGenInEq().
void tasks::qp::reduceA (const Eigen::MatrixXd & AFull, Eigen::MatrixXd & A, const std::vector< int > & fullToReduced, const std::vector< int > & reducedToFull, const std::vector< std::tuple< int, int, double >> & dependencies) inline
Reduce \(A \) matrix based on the dependencies list.
void tasks::qp::reduceBound (const Eigen::VectorXd & XLFull, Eigen::VectorXd & XL, const Eigen::VectorXd & XUFull, Eigen::VectorXd & XU, const std::vector< int > & fullToReduced, const std::vector< int > & reducedToFull, const std::vector< std::tuple< int, int, double >> & dependencies) inline
Reduce bounds vector based on the dependencies list.
If alpha is negative, the upper/lower bounds should be inverted
void tasks::qp::reduceQC (const Eigen::MatrixXd & QFull, const Eigen::VectorXd & CFull, Eigen::MatrixXd & Q, Eigen::VectorXd & C, const std::vector< int > & fullToReduced, const std::vector< int > & reducedToFull, const std::vector< std::tuple< int, int, double >> & dependencies) inline
Reduce \(Q \) matrix and the \(c \) vector based on the dependencies list.
TASKS_DLLAPI sch::Matrix4x4 tasks::qp::tosch (const sva::PTransformd & t)
Convert a sch-core transformation matrix to a sva::PTransformd matrix.
Variable Documentation
const double tasks::qp::DIAG_CONSTANT = 1e-4 static
Referenced by fillQC().