tasks::qp::constr_traits< GenInequality > Struct Template Reference
tasks::qp::constr_traits< GenInequality > Struct Template Reference
#include <Tasks/QPSolver.h>
Static Public Member Functions
static int maxLines (const GenInequality *constr)
static int nrLines (const GenInequality *constr)
static std::string name (const GenInequality *constr)
static std::string desc (GenInequality *constr, const std::vector< rbd::MultiBody > &mbs, int i)
Member Function Documentation
desc()
static std::string tasks::qp::constr_traits< GenInequality >::desc (GenInequality * constr, const std::vector< rbd::MultiBody > & mbs, int i) inline static
References tasks::qp::GenInequality::descGenInEq().
maxLines()
static int tasks::qp::constr_traits< GenInequality >::maxLines (const GenInequality * constr) inline static
References tasks::qp::GenInequality::maxGenInEq().
name()
static std::string tasks::qp::constr_traits< GenInequality >::name (const GenInequality * constr) inline static
References tasks::qp::GenInequality::nameGenInEq().
nrLines()
static int tasks::qp::constr_traits< GenInequality >::nrLines (const GenInequality * constr) inline static
References tasks::qp::GenInequality::nrGenInEq().