tasks::qp::constr_traits< Equality > Struct Template Reference
tasks::qp::constr_traits< Equality > Struct Template Reference
#include <Tasks/QPSolver.h>
Static Public Member Functions
static int maxLines (const Equality *constr)
static int nrLines (const Equality *constr)
static std::string name (const Equality *constr)
static std::string desc (Equality *constr, const std::vector< rbd::MultiBody > &mbs, int i)
Member Function Documentation
desc()
static std::string tasks::qp::constr_traits< Equality >::desc (Equality * constr, const std::vector< rbd::MultiBody > & mbs, int i) inline static
References tasks::qp::Equality::descEq().
maxLines()
static int tasks::qp::constr_traits< Equality >::maxLines (const Equality * constr) inline static
References tasks::qp::Equality::maxEq().
name()
static std::string tasks::qp::constr_traits< Equality >::name (const Equality * constr) inline static
References tasks::qp::Equality::nameEq().
nrLines()
static int tasks::qp::constr_traits< Equality >::nrLines (const Equality * constr) inline static
References tasks::qp::Equality::nrEq().