tasks::qp::constr_traits< Inequality > Struct Template Reference
tasks::qp::constr_traits< Inequality > Struct Template Reference
#include <Tasks/QPSolver.h>
Static Public Member Functions
static int maxLines (const Inequality *constr)
static int nrLines (const Inequality *constr)
static std::string name (const Inequality *constr)
static std::string desc (Inequality *constr, const std::vector< rbd::MultiBody > &mbs, int i)
Member Function Documentation
desc()
static std::string tasks::qp::constr_traits< Inequality >::desc (Inequality * constr, const std::vector< rbd::MultiBody > & mbs, int i) inline static
References tasks::qp::Inequality::descInEq().
maxLines()
static int tasks::qp::constr_traits< Inequality >::maxLines (const Inequality * constr) inline static
References tasks::qp::Inequality::maxInEq().
name()
static std::string tasks::qp::constr_traits< Inequality >::name (const Inequality * constr) inline static
References tasks::qp::Inequality::nameInEq().
nrLines()
static int tasks::qp::constr_traits< Inequality >::nrLines (const Inequality * constr) inline static
References tasks::qp::Inequality::nrInEq().