tasks::qp::RelativeDistTask Class Reference
tasks::qp::RelativeDistTask Class Reference
#include <Tasks/QPTasks.h>
Public Member Functions
RelativeDistTask (const std::vector< rbd::MultiBody > &mbs, const int rIndex, const double timestep, tasks::RelativeDistTask::rbInfo &rbi1, tasks::RelativeDistTask::rbInfo &rbi2, const Eigen::Vector3d &u1=Eigen::Vector3d::Zero(), const Eigen::Vector3d &u2=Eigen::Vector3d::Zero())
tasks::RelativeDistTask & task ()
void robotPoint (const rbd::MultiBody &mb, const std::string &bName, const Eigen::Vector3d &point)
void envPoint (const rbd::MultiBody &mb, const std::string &bName, const Eigen::Vector3d &point)
void vector (const rbd::MultiBody &mb, const std::string &bName, const Eigen::Vector3d &u)
virtual int dim () override
virtual void update (const std::vector< rbd::MultiBody > &mbs, const std::vector< rbd::MultiBodyConfig > &mbcs, const SolverData &data) override
virtual const Eigen::MatrixXd & jac () override
virtual const Eigen::VectorXd & eval () override
virtual const Eigen::VectorXd & speed () override
virtual const Eigen::VectorXd & normalAcc () override
Public Member Functions inherited from tasks::qp::HighLevelTask
virtual ~HighLevelTask ()
Constructor & Destructor Documentation
RelativeDistTask()
tasks::qp::RelativeDistTask::RelativeDistTask (const std::vector< rbd::MultiBody > & mbs, const int rIndex, const double timestep, tasks::RelativeDistTask::rbInfo & rbi1, tasks::RelativeDistTask::rbInfo & rbi2, const Eigen::Vector3d & u1 = Eigen::Vector3d::Zero(), const Eigen::Vector3d & u2 = Eigen::Vector3d::Zero())
Member Function Documentation
dim()
virtual int tasks::qp::RelativeDistTask::dim () override virtual
Implements tasks::qp::HighLevelTask.
envPoint()
void tasks::qp::RelativeDistTask::envPoint (const rbd::MultiBody & mb, const std::string & bName, const Eigen::Vector3d & point) inline
References rbd::MultiBody::bodyIndexByName().
eval()
virtual const Eigen::VectorXd& tasks::qp::RelativeDistTask::eval () override virtual
Implements tasks::qp::HighLevelTask.
jac()
virtual const Eigen::MatrixXd& tasks::qp::RelativeDistTask::jac () override virtual
Implements tasks::qp::HighLevelTask.
normalAcc()
virtual const Eigen::VectorXd& tasks::qp::RelativeDistTask::normalAcc () override virtual
Implements tasks::qp::HighLevelTask.
robotPoint()
void tasks::qp::RelativeDistTask::robotPoint (const rbd::MultiBody & mb, const std::string & bName, const Eigen::Vector3d & point) inline
References rbd::MultiBody::bodyIndexByName().
speed()
virtual const Eigen::VectorXd& tasks::qp::RelativeDistTask::speed () override virtual
Implements tasks::qp::HighLevelTask.
task()
tasks::RelativeDistTask& tasks::qp::RelativeDistTask::task () inline
update()
virtual void tasks::qp::RelativeDistTask::update (const std::vector< rbd::MultiBody > & mbs, const std::vector< rbd::MultiBodyConfig > & mbcs, const SolverData & data) override virtual
Implements tasks::qp::HighLevelTask.
vector()
void tasks::qp::RelativeDistTask::vector (const rbd::MultiBody & mb, const std::string & bName, const Eigen::Vector3d & u) inline
References rbd::MultiBody::bodyIndexByName().