var annotated_dup =
[
    [ "tasks", "namespacetasks.html", [
      [ "qp", "namespacetasks_1_1qp.html", [
        [ "LSSOLQPSolver", "classtasks_1_1qp_1_1LSSOLQPSolver.html", "classtasks_1_1qp_1_1LSSOLQPSolver" ],
        [ "QLDQPSolver", "classtasks_1_1qp_1_1QLDQPSolver.html", "classtasks_1_1qp_1_1QLDQPSolver" ],
        [ "GenQPSolver", "classtasks_1_1qp_1_1GenQPSolver.html", "classtasks_1_1qp_1_1GenQPSolver" ],
        [ "JointLimitsConstr", "classtasks_1_1qp_1_1JointLimitsConstr.html", "classtasks_1_1qp_1_1JointLimitsConstr" ],
        [ "DamperJointLimitsConstr", "classtasks_1_1qp_1_1DamperJointLimitsConstr.html", "classtasks_1_1qp_1_1DamperJointLimitsConstr" ],
        [ "CollisionConstr", "classtasks_1_1qp_1_1CollisionConstr.html", "classtasks_1_1qp_1_1CollisionConstr" ],
        [ "CoMIncPlaneConstr", "classtasks_1_1qp_1_1CoMIncPlaneConstr.html", "classtasks_1_1qp_1_1CoMIncPlaneConstr" ],
        [ "GripperTorqueConstr", "classtasks_1_1qp_1_1GripperTorqueConstr.html", "classtasks_1_1qp_1_1GripperTorqueConstr" ],
        [ "BoundedSpeedConstr", "classtasks_1_1qp_1_1BoundedSpeedConstr.html", "classtasks_1_1qp_1_1BoundedSpeedConstr" ],
        [ "ImageConstr", "classtasks_1_1qp_1_1ImageConstr.html", "classtasks_1_1qp_1_1ImageConstr" ],
        [ "ContactConstrCommon", "classtasks_1_1qp_1_1ContactConstrCommon.html", "classtasks_1_1qp_1_1ContactConstrCommon" ],
        [ "ContactConstr", "classtasks_1_1qp_1_1ContactConstr.html", "classtasks_1_1qp_1_1ContactConstr" ],
        [ "ContactAccConstr", "classtasks_1_1qp_1_1ContactAccConstr.html", "classtasks_1_1qp_1_1ContactAccConstr" ],
        [ "ContactSpeedConstr", "classtasks_1_1qp_1_1ContactSpeedConstr.html", "classtasks_1_1qp_1_1ContactSpeedConstr" ],
        [ "ContactPosConstr", "classtasks_1_1qp_1_1ContactPosConstr.html", "classtasks_1_1qp_1_1ContactPosConstr" ],
        [ "FrictionCone", "structtasks_1_1qp_1_1FrictionCone.html", "structtasks_1_1qp_1_1FrictionCone" ],
        [ "ContactId", "structtasks_1_1qp_1_1ContactId.html", "structtasks_1_1qp_1_1ContactId" ],
        [ "UnilateralContact", "structtasks_1_1qp_1_1UnilateralContact.html", "structtasks_1_1qp_1_1UnilateralContact" ],
        [ "BilateralContact", "structtasks_1_1qp_1_1BilateralContact.html", "structtasks_1_1qp_1_1BilateralContact" ],
        [ "PositiveLambda", "classtasks_1_1qp_1_1PositiveLambda.html", "classtasks_1_1qp_1_1PositiveLambda" ],
        [ "MotionConstrCommon", "classtasks_1_1qp_1_1MotionConstrCommon.html", "classtasks_1_1qp_1_1MotionConstrCommon" ],
        [ "MotionConstr", "classtasks_1_1qp_1_1MotionConstr.html", "classtasks_1_1qp_1_1MotionConstr" ],
        [ "SpringJoint", "structtasks_1_1qp_1_1SpringJoint.html", "structtasks_1_1qp_1_1SpringJoint" ],
        [ "MotionSpringConstr", "classtasks_1_1qp_1_1MotionSpringConstr.html", "classtasks_1_1qp_1_1MotionSpringConstr" ],
        [ "MotionPolyConstr", "classtasks_1_1qp_1_1MotionPolyConstr.html", "classtasks_1_1qp_1_1MotionPolyConstr" ],
        [ "QPSolver", "classtasks_1_1qp_1_1QPSolver.html", "classtasks_1_1qp_1_1QPSolver" ],
        [ "Constraint", "classtasks_1_1qp_1_1Constraint.html", "classtasks_1_1qp_1_1Constraint" ],
        [ "ConstraintFunction", "classtasks_1_1qp_1_1ConstraintFunction.html", "classtasks_1_1qp_1_1ConstraintFunction" ],
        [ "Equality", "classtasks_1_1qp_1_1Equality.html", "classtasks_1_1qp_1_1Equality" ],
        [ "Inequality", "classtasks_1_1qp_1_1Inequality.html", "classtasks_1_1qp_1_1Inequality" ],
        [ "GenInequality", "classtasks_1_1qp_1_1GenInequality.html", "classtasks_1_1qp_1_1GenInequality" ],
        [ "Bound", "classtasks_1_1qp_1_1Bound.html", "classtasks_1_1qp_1_1Bound" ],
        [ "Task", "classtasks_1_1qp_1_1Task.html", "classtasks_1_1qp_1_1Task" ],
        [ "HighLevelTask", "classtasks_1_1qp_1_1HighLevelTask.html", "classtasks_1_1qp_1_1HighLevelTask" ],
        [ "constr_traits", "structtasks_1_1qp_1_1constr__traits.html", null ],
        [ "constr_traits< Equality >", "structtasks_1_1qp_1_1constr__traits_3_01Equality_01_4.html", null ],
        [ "constr_traits< Inequality >", "structtasks_1_1qp_1_1constr__traits_3_01Inequality_01_4.html", null ],
        [ "constr_traits< GenInequality >", "structtasks_1_1qp_1_1constr__traits_3_01GenInequality_01_4.html", null ],
        [ "SolverData", "classtasks_1_1qp_1_1SolverData.html", "classtasks_1_1qp_1_1SolverData" ],
        [ "SetPointTaskCommon", "classtasks_1_1qp_1_1SetPointTaskCommon.html", "classtasks_1_1qp_1_1SetPointTaskCommon" ],
        [ "SetPointTask", "classtasks_1_1qp_1_1SetPointTask.html", "classtasks_1_1qp_1_1SetPointTask" ],
        [ "TrackingTask", "classtasks_1_1qp_1_1TrackingTask.html", "classtasks_1_1qp_1_1TrackingTask" ],
        [ "TrajectoryTask", "classtasks_1_1qp_1_1TrajectoryTask.html", "classtasks_1_1qp_1_1TrajectoryTask" ],
        [ "PIDTask", "classtasks_1_1qp_1_1PIDTask.html", "classtasks_1_1qp_1_1PIDTask" ],
        [ "TargetObjectiveTask", "classtasks_1_1qp_1_1TargetObjectiveTask.html", "classtasks_1_1qp_1_1TargetObjectiveTask" ],
        [ "JointsSelector", "classtasks_1_1qp_1_1JointsSelector.html", "classtasks_1_1qp_1_1JointsSelector" ],
        [ "JointStiffness", "structtasks_1_1qp_1_1JointStiffness.html", "structtasks_1_1qp_1_1JointStiffness" ],
        [ "JointGains", "structtasks_1_1qp_1_1JointGains.html", "structtasks_1_1qp_1_1JointGains" ],
        [ "TorqueTask", "classtasks_1_1qp_1_1TorqueTask.html", "classtasks_1_1qp_1_1TorqueTask" ],
        [ "PostureTask", "classtasks_1_1qp_1_1PostureTask.html", "classtasks_1_1qp_1_1PostureTask" ],
        [ "PositionTask", "classtasks_1_1qp_1_1PositionTask.html", "classtasks_1_1qp_1_1PositionTask" ],
        [ "OrientationTask", "classtasks_1_1qp_1_1OrientationTask.html", "classtasks_1_1qp_1_1OrientationTask" ],
        [ "TransformTaskCommon", "classtasks_1_1qp_1_1TransformTaskCommon.html", "classtasks_1_1qp_1_1TransformTaskCommon" ],
        [ "SurfaceTransformTask", "classtasks_1_1qp_1_1SurfaceTransformTask.html", "classtasks_1_1qp_1_1SurfaceTransformTask" ],
        [ "TransformTask", "classtasks_1_1qp_1_1TransformTask.html", "classtasks_1_1qp_1_1TransformTask" ],
        [ "SurfaceOrientationTask", "classtasks_1_1qp_1_1SurfaceOrientationTask.html", "classtasks_1_1qp_1_1SurfaceOrientationTask" ],
        [ "GazeTask", "classtasks_1_1qp_1_1GazeTask.html", "classtasks_1_1qp_1_1GazeTask" ],
        [ "PositionBasedVisServoTask", "classtasks_1_1qp_1_1PositionBasedVisServoTask.html", "classtasks_1_1qp_1_1PositionBasedVisServoTask" ],
        [ "CoMTask", "classtasks_1_1qp_1_1CoMTask.html", "classtasks_1_1qp_1_1CoMTask" ],
        [ "MultiCoMTask", "classtasks_1_1qp_1_1MultiCoMTask.html", "classtasks_1_1qp_1_1MultiCoMTask" ],
        [ "MultiRobotTransformTask", "classtasks_1_1qp_1_1MultiRobotTransformTask.html", "classtasks_1_1qp_1_1MultiRobotTransformTask" ],
        [ "MomentumTask", "classtasks_1_1qp_1_1MomentumTask.html", "classtasks_1_1qp_1_1MomentumTask" ],
        [ "ContactTask", "classtasks_1_1qp_1_1ContactTask.html", "classtasks_1_1qp_1_1ContactTask" ],
        [ "GripperTorqueTask", "classtasks_1_1qp_1_1GripperTorqueTask.html", "classtasks_1_1qp_1_1GripperTorqueTask" ],
        [ "LinVelocityTask", "classtasks_1_1qp_1_1LinVelocityTask.html", "classtasks_1_1qp_1_1LinVelocityTask" ],
        [ "OrientationTrackingTask", "classtasks_1_1qp_1_1OrientationTrackingTask.html", "classtasks_1_1qp_1_1OrientationTrackingTask" ],
        [ "RelativeDistTask", "classtasks_1_1qp_1_1RelativeDistTask.html", "classtasks_1_1qp_1_1RelativeDistTask" ],
        [ "VectorOrientationTask", "classtasks_1_1qp_1_1VectorOrientationTask.html", "classtasks_1_1qp_1_1VectorOrientationTask" ]
      ] ],
      [ "QBound", "structtasks_1_1QBound.html", "structtasks_1_1QBound" ],
      [ "AlphaBound", "structtasks_1_1AlphaBound.html", "structtasks_1_1AlphaBound" ],
      [ "AlphaDBound", "structtasks_1_1AlphaDBound.html", "structtasks_1_1AlphaDBound" ],
      [ "AlphaDDBound", "structtasks_1_1AlphaDDBound.html", "structtasks_1_1AlphaDDBound" ],
      [ "TorqueBound", "structtasks_1_1TorqueBound.html", "structtasks_1_1TorqueBound" ],
      [ "TorqueDBound", "structtasks_1_1TorqueDBound.html", "structtasks_1_1TorqueDBound" ],
      [ "PolyTorqueBound", "structtasks_1_1PolyTorqueBound.html", "structtasks_1_1PolyTorqueBound" ],
      [ "PositionTask", "classtasks_1_1PositionTask.html", "classtasks_1_1PositionTask" ],
      [ "OrientationTask", "classtasks_1_1OrientationTask.html", "classtasks_1_1OrientationTask" ],
      [ "TransformTaskCommon", "classtasks_1_1TransformTaskCommon.html", "classtasks_1_1TransformTaskCommon" ],
      [ "SurfaceTransformTask", "classtasks_1_1SurfaceTransformTask.html", "classtasks_1_1SurfaceTransformTask" ],
      [ "TransformTask", "classtasks_1_1TransformTask.html", "classtasks_1_1TransformTask" ],
      [ "MultiRobotTransformTask", "classtasks_1_1MultiRobotTransformTask.html", "classtasks_1_1MultiRobotTransformTask" ],
      [ "SurfaceOrientationTask", "classtasks_1_1SurfaceOrientationTask.html", "classtasks_1_1SurfaceOrientationTask" ],
      [ "GazeTask", "classtasks_1_1GazeTask.html", "classtasks_1_1GazeTask" ],
      [ "PositionBasedVisServoTask", "classtasks_1_1PositionBasedVisServoTask.html", "classtasks_1_1PositionBasedVisServoTask" ],
      [ "PostureTask", "classtasks_1_1PostureTask.html", "classtasks_1_1PostureTask" ],
      [ "CoMTask", "classtasks_1_1CoMTask.html", "classtasks_1_1CoMTask" ],
      [ "MultiCoMTask", "classtasks_1_1MultiCoMTask.html", "classtasks_1_1MultiCoMTask" ],
      [ "MomentumTask", "classtasks_1_1MomentumTask.html", "classtasks_1_1MomentumTask" ],
      [ "LinVelocityTask", "classtasks_1_1LinVelocityTask.html", "classtasks_1_1LinVelocityTask" ],
      [ "OrientationTrackingTask", "classtasks_1_1OrientationTrackingTask.html", "classtasks_1_1OrientationTrackingTask" ],
      [ "RelativeDistTask", "classtasks_1_1RelativeDistTask.html", "classtasks_1_1RelativeDistTask" ],
      [ "VectorOrientationTask", "classtasks_1_1VectorOrientationTask.html", "classtasks_1_1VectorOrientationTask" ]
    ] ]
];